
sudo: required
dist: xenial

language:
  - cpp

compiler:
  - gcc
  
before_install:
  - sudo apt-add-repository -y ppa:beineri/opt-qt-5.15.0-xenial
  - travis_wait 30 sudo apt-get -qq update
  - sudo apt-get -qq install qt515base
  - source /opt/qt515/bin/qt515-env.sh

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - cmake
      - freeglut3-dev
      
after_success:
  - cd ${TRAVIS_BUILD_DIR}
  - lcov --directory . --capture --output-file coverage.info coverage info
  - lcov --remove coverage.info '/usr/*' --output-file coverage.info
  - lcov --list coverage.info
  - bash <(curl -s https://codecov.io/bash)

script:
  - |
    mkdir build || { exit 1; }; \
    cd build || { exit 1; }; \
    cmake -DENABLE_COVERAGE=ON -DCMAKE_BUILD_TYPE=Debug .. || { exit 1; }; \
    make || { exit 1; }; \
    ctest --output-on-failure --verbose || { exit 1; };
