
sudo: required
dist: xenial

language:
  - cpp

compiler:
  - gcc
  
before_install:
  - sudo apt-add-repository -y ppa:beineri/opt-qt-5.15.0-xenial &&
  - travis_wait 30 sudo apt-get -qq update &&
  - sudo apt-get -qq install qt515base &&
  - source /opt/qt515/bin/qt515-env.sh

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - cmake

script:
  - |
    mkdir build || { exit 1; }; \
    cd build || { exit 1; }; \
    cmake -DENABLE_COVERAGE=ON -DCMAKE_BUILD_TYPE=Debug .. || { exit 1; }; \
    make || { exit 1; }; \
    make coveralls || { exit 1; };
